export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",

  INVALID_LOCATION: "INVALID_LOCATION",
  LOCATION_LOOKUP_FAILED: "LOCATION_LOOKUP_FAILED",

  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",

  WEATHER_FETCH_FAILED: "WEATHER_FETCH_FAILED",
  WEATHER_API_ERROR: "WEATHER_API_ERROR",

  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",

  DATABASE_ERROR: "DATABASE_ERROR",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
});